backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images"

collections:
    - label: "Pages"
      name: "pages"
      files:
      - name: "blog" # Used in routes, e.g., /admin/collections/blog
        label: "Blog" # Used in the UI
        file: "_posts/blog/data.json"
        extension: "json"
        create: true # Allow users to create new documents in this collection
        description: "A blog"
        fields: # The fields for each document, usually in front matter
          - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Featured Image", name: "thumbnail", widget: "image"}
          - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
          - {label: "Body", name: "body", widget: "markdown"}