backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)

media_folder: "../images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images"

collections:
    - label: "Pages"
      name: "pages"
      files:
      - file: "_posts/news/index.md"
        label: "News" # Used in the UI
        name: "news" # Used in routes, e.g., /admin/collections/blog
        description: "News page"
        fields: # The fields for each document, usually in front matter
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Blurbs, name: blurbs, widget: list, fields: [{label: "Title", name: "title", widget: "string"}, {label: Body, name: body, widget: markdown}, {label: Image, name: image, widget: image}, {label: "Publish Date", name: "date", widget: "datetime"}]}]}